on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  imageBuildAndPush:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment: ${{ inputs.environment }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            balamani3010/buildandpushtest:${{ github.sha }}-${{ vars.env_name }}
            balamani3010/buildandpushtest:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test1
        id: time
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDDHHmmssSSS"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "${{ vars.env }}-${{ steps.time.outputs.time }}"
