---
name: "testing deployment"

on:
  workflow_call:
    inputs:
      deployment_environment:
        required: true
        type: string

jobs:
  deployment-${{ inputs.deployment_environment }}:
    environment: ${{ inputs.deployment_environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Deployment to ${{ inputs.deployment_environment }}
        run: |
          echo "the variable value is: ${{var.ENV_NAME}}"
