on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  imageBuildAndPush:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment: ${{ inputs.environment }}

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            balamani3010/buildandpushtest:${{ github.sha }}-${{ vars.env_name }}
            balamani3010/buildandpushtest:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test1
        id: time
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDDHHmmssSSS"

      # - name: Create Tag
      #   uses: negz/create-tag@v1
      #   with:
      #     version: "${{ vars.env_name }}-${{ steps.time.outputs.time }}"
      #     message: "test"
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: "refs/tags/${{ vars.env_name }}-${{ steps.time.outputs.time }}",
      #         sha: context.sha
      #       })
      - name: commit
        run: |
          echo "commit id: ${{ github.sha }}"
          echo "directory: ${{fromJson(vars.CONTAINERCOMMAND).dbScriptDirectory}}"
          echo "missedScript: ${{fromJson(vars.CONTAINERCOMMAND).missedScriptName}}"
          echo "branch: ${{ github.ref_name }}"
