---
name: "testing deployment"

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  deployment-nonprod:
    environment: nonprod
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment to non-prod
        run: |
          echo "the variable value is: ${{var.TEST}}"

  deployment-prod:
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment to non-prod
        run: |
          echo "the variable value is: ${{var.TEST}}"
