---
name: "testing deployment"

on:
  push:
    branches:
      - main
      - develop

jobs:
  ReuseableMatrixJobForDeployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [DEV, TEST, PROD]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deployment
        uses: .github/workflows/deploy.yml
        with:
          deployment_environment: ${{ matrix.target }}
